# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool: terraform

pr:
- main
- features/**

variables:
  sourcepath: '$(System.DefaultWorkingDirectory)\Infra'
  
steps:
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)\Infra'
      backendAzureRmUseEntraIdForAuthentication: false
      backendServiceArm: 'jkpipe'
      backendAzureRmResourceGroupName: 'terraformstorage'
      backendAzureRmStorageAccountName: 'terraformstoragejk'
      backendAzureRmContainerName: 'tfstate'
      backendAzureRmKey: 'dev.tfstate'